apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  containers:
    - image: mongo:latest
      name: mongodb-in-kubernetes
      volumeMounts:
      - name:  host-volume
        mountPath: "/data/db"
  
  volumes:
    # - name:  empty-volume
    #   emptyDir: { }

    # - name: nfs-volume
    #   nfs:
    #     server: 10.108.211.244
    #     path: /

    - name: host-volume
      hostPath:
        path: /mongo/database
---

apiVersion: v1
kind: Service
metadata:
  name: mongo-service-kubernetes
spec:
  type: NodePort
  selector:
    app: mongdb
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017